name: Signing

on:
  push:
    branches:
      - main

jobs:
  sign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install GPG
        run: sudo apt-get install gnupg
      - name: Import GPG key
        run: echo "${{ secrets.SIGNING_KEY }}" | base64 --decode | gpg --import
      - name: Sign source code
        run: |
          find . -type f -name '*.cs' -exec gpg --yes --detach-sign --armor {} \;
          git add .
          git commit -m "Signed source code"
          git push origin HEAD
